version: "3"

services:

  memory_commander:

    image: ghcr.io/joeferner/redis-commander:latest

    ports:

      - ${MEMORY_COMMANDER_PORT}:8081

    restart: always

    environment:

      TZ: ${TZ}

      REDIS_HOST: memory
      REDIS_PASSWORD_FILE: /run/secrets/memory
      HTTP_USER: ${DATABASE_USERNAME}
      HTTP_PASSWORD_FILE: /run/secrets/memory

    secrets:

      - memory

    depends_on:

      - memory

  database_mssql_adminer:

    image: adminer:latest

    ports:

      - ${DATABASE_MSSQL_ADMINER_PORT}:8080

    restart: always

    environment:

      TZ: ${TZ}

      ADMINER_DEFAULT_SERVER: database_mssql

    secrets:

      - database_mssql

    depends_on:

      - database_mssql
